# ML-02 — Research Question and Provisional Lane

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane (or freestyle) and why

I am choosing the **Refresh / Content Opportunity Scoring** lane for now. It fits the starter pipeline, the action is easy to explain, and the output is useful to a real person: a ranked review queue of pages that look worth refreshing first. I am not trying to "predict Google"; I am trying to rank pages for review using observed demand, position, freshness, and decline signals. That gives me a concrete decision, a clear actor, and enough room to improve the ordering without pretending the model is the product.

This is provisional. I can still change lanes through Week 4, but this one looks like a strong fit for the next seven weeks because the starter data already contains the kind of signals this lane needs.

In [1]:
import pandas as pd

starter = pd.read_csv('../../data/raw/content_refresh_anonymized.csv')

summary = pd.DataFrame(
    {
        'metric': [
            'rows',
            'clients',
            'declining pages',
            'pages with impressions > 0',
            'pages with avg_position > 0',
        ],
        'value': [
            len(starter),
            starter['client_id'].nunique(),
            (starter['trend_direction'] == 'down').sum(),
            (starter['impressions_90d'] > 0).sum(),
            (starter['avg_position'] > 0).sum(),
        ],
    }
)

summary

                        metric  value
0                         rows  30000
1                      clients     32
2              declining pages  16262
3   pages with impressions > 0  30000
4  pages with avg_position > 0  28795

## 2. The question: decision, action, cost of a wrong call

The decision I want to improve is: **which content page should get reviewed and refreshed first?** The person acting on the output is an editor, content strategist, or SEO analyst. They would use the ranking to choose the next pages to inspect, update titles or copy, and decide whether a page deserves a more serious rewrite.

A wrong recommendation has a real cost. A false positive wastes editorial time on pages that do not need attention. A false negative leaves a declining page with demand untouched, which can mean lost clicks and slower recovery. That is why the output should be a ranked queue, not a hard yes/no verdict.

The right language here is decision-support: this work should help someone prioritize effort, not replace judgment.

In [2]:
frame = pd.DataFrame(
    {
        'item': ['decision', 'actor', 'action', 'wrong_call_cost'],
        'value': [
            'which page should be reviewed and refreshed first',
            'editor, content strategist, or SEO analyst',
            'inspect the highest-ranked pages and update titles, copy, or structure',
            'wasted editorial effort on low-opportunity pages or missed recovery on pages with demand',
        ],
    }
)

frame

              item                                              value
0         decision  which page should be reviewed and refreshed first
1            actor         editor, content strategist, or SEO analyst
2           action  inspect the highest-ranked pages and update ti...
3  wrong_call_cost  wasted editorial effort on low-opportunity pag...

## 3. Quick look at the data (2-3 real numbers)

The code cell below loads the starter CSV and prints the exact counts that make this lane worth pursuing: total rows, unique clients, and the number of pages already labeled as declining. Those numbers should make it obvious that there is enough signal to rank, not just enough data to memorize.

I am also checking how many pages have nonzero impressions and nonzero average position, because this lane only makes sense if the data contains enough visible pages to prioritize.

Run the code cell below to see the real counts from the starter dataset.

In [3]:
quick_view = pd.DataFrame(
    {
        'metric': [
            'rows',
            'unique clients',
            'declining pages',
        ],
        'value': [
            len(starter),
            starter['client_id'].nunique(),
            (starter['trend_direction'] == 'down').sum(),
        ],
    }
)

visibility_check = pd.DataFrame(
    {
        'metric': [
            'pages with impressions > 0',
            'pages with avg_position > 0',
        ],
        'value': [
            (starter['impressions_90d'] > 0).sum(),
            (starter['avg_position'] > 0).sum(),
        ],
    }
)

print('Starter dataset counts:')
print(quick_view.to_string(index=False))
print()
print('Visibility check:')
print(visibility_check.to_string(index=False))

Starter dataset counts:
         metric  value
           rows  30000
 unique clients     32
declining pages  16262

Visibility check:
                     metric  value
 pages with impressions > 0  30000
pages with avg_position > 0  28795

## 4. Careful words: what I can and can't claim

I can claim that my ranking is based on observed signals, that it orders pages in a directional way, and that it is meant to support a decision. I can also claim that the output is testable against future observed outcomes such as later traffic change or later recovery.

I cannot claim causal proof. I cannot claim to "predict Google." I cannot say a page will definitely recover because the score is high. The notebook should stay honest about that boundary: it is a prioritization tool, not a theory of the search engine.

The safest summary is that this project should produce decision-support evidence, not final truth.

In [4]:
claims = pd.DataFrame(
    {
        'claim_type': ['can_claim', 'can_claim', 'cannot_claim', 'cannot_claim'],
        'statement': [
            'This ranking is based on observed signals.',
            'The output is decision-support for prioritizing review.',
            'This notebook does not prove causality.',
            'This notebook does not "predict Google".',
        ],
    }
)

claims

     claim_type                                          statement
0     can_claim         This ranking is based on observed signals.
1     can_claim  The output is decision-support for prioritizin...
2  cannot_claim            This notebook does not prove causality.
3  cannot_claim           This notebook does not "predict Google".

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.